name: MainDeployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r cm-int-roles.zip cm-roles
      - uses: actions/upload-artifact@v2
        with:
          name: cm-int-roles.zip
