name: MainDeployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dist/cm-int-roles.zip cm-roles
      - name: zip DCConfiguration Folder
        run: |
          cd DSC
          rm -fv DCConfiguration.zip
          zip -qq -r DCConfiguration.zip *
          zip -qq -r ../dist/DSC-WF.zip *   
      - uses: actions/upload-artifact@v2
        with:
          name: role-zip
          path: dist/cm-int-roles.zip          
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: dist
          container_name: ${{ secrets.AZ_STOR_CONT }}
          connection_string: ${{ secrets.AZ_STOR_CONN_STR }}
          overwrite: 'true'