name: MainDeployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r roles.zip .
      - uses: actions/upload-artifact@v2
        with:
          name: roles.zip
